<!--#include file="Charset.Asp" -->
<%
Const EnableCopy = False
Const EnableBackstageCode = True
Const EnableSiteManageCode = False
Const SiteManageCode = ""
Const ClassSeoISPY = False
Const Separated = "-"
Const JMailDisplay = False
Const JMailSMTP = ""
Const JMailUser = ""
Const JMailPass = ""
Const JMailName = ""
Const JMailInFrom = ""
Const JMailOutFrom = ""
Const JMailTitle = "客户咨询"
Const EnableViews = True
Const EnableSeo = True
Const mStatus = False
Const SysRootDir = "/"
Const HTMLName = "html"
Const KeyicmsV = "V1.06 RC"
%>