<%
'=========================================================
' 功能注释 : 系统后台语言文档(版本信息)
'=========================================================
Dim Keyicms_Lang_Copyright(14)
    Keyicms_Lang_Copyright(1) = "网站管理系统"
    Keyicms_Lang_Copyright(2) = ""
    Keyicms_Lang_Copyright(3) = ""
    Keyicms_Lang_Copyright(4) = "程序版本"
    Keyicms_Lang_Copyright(5) = "官方网站"
    Keyicms_Lang_Copyright(6) = "官方公告"
    Keyicms_Lang_Copyright(7) = "最新版本"
    Keyicms_Lang_Copyright(8) = "当前版本"
    Keyicms_Lang_Copyright(9) = "旗舰版"
    Keyicms_Lang_Copyright(10) = "免费版"
    Keyicms_Lang_Copyright(11) = "专业版"
    Keyicms_Lang_Copyright(12) = "开发版"
    Keyicms_Lang_Copyright(13) = ""
    Keyicms_Lang_Copyright(14) = "当前位置"	
'=========================================================
' 功能注释 : 系统后台语言文档(版本信息)
'=========================================================
Dim Keyicms_Lang_System(33)
    Keyicms_Lang_System(1) = "系统设置"
	Keyicms_Lang_System(2) = "系统参数设置"
	Keyicms_Lang_System(3) = "基础设置"
	Keyicms_Lang_System(4) = "网站安全设置"
    Keyicms_Lang_System(5) = "功能模块调用条数设置"
	Keyicms_Lang_System(6) = "静态化处理设置"
	Keyicms_Lang_System(7) = "SEO设置"
	Keyicms_Lang_System(8) = "其他信息设置"
    Keyicms_Lang_System(9) = "核心管理"
	Keyicms_Lang_System(10) = "网站参数设置"
	Keyicms_Lang_System(11) = "网站信息设置"
	Keyicms_Lang_System(12) = "导航设置"
	Keyicms_Lang_System(13) = "手机网站设置"
	Keyicms_Lang_System(14) = "功能模块设置"
    Keyicms_Lang_System(15) = "关于我们"
	Keyicms_Lang_System(16) = "学院图片模块"
	Keyicms_Lang_System(17) = "新闻、公告、学工信息模块"
	Keyicms_Lang_System(18) = "扩展资源模块"
    Keyicms_Lang_System(19) = "服务模块"
	Keyicms_Lang_System(20) = "团队模块"
    Keyicms_Lang_System(21) = "就业信息模块"
	Keyicms_Lang_System(22) = "其他信息模块"
	Keyicms_Lang_System(23) = "网站应用"
	Keyicms_Lang_System(24) = "模板管理"
    Keyicms_Lang_System(25) = "管理员管理"
	
	Keyicms_Lang_System(26) = "您没有管理该模块的权限！"
	Keyicms_Lang_System(27) = "选择图片"
	Keyicms_Lang_System(28) = "数据库记录读取错误！"
    Keyicms_Lang_System(29) = "操作错误"
    Keyicms_Lang_System(30) = "启用"
    Keyicms_Lang_System(31) = "不启用"
	
	Keyicms_Lang_System(32) = "返回上一页"
'=========================================================
' 功能注释 : 系统后台语言文档(网站信息设置)
'=========================================================
Dim Keyicms_Lang_MainSite(27)
    Keyicms_Lang_MainSite(0) = "网站标题"
	Keyicms_Lang_MainSite(1) = "网站网址"
	Keyicms_Lang_MainSite(2) = "网站ICP备案号"
	Keyicms_Lang_MainSite(3) = "网站LOGO设置"
	Keyicms_Lang_MainSite(4) = "学院二维码设置"
	Keyicms_Lang_MainSite(5) = "第三方代码调用接口"
	Keyicms_Lang_MainSite(6) = "网站关键词"
	Keyicms_Lang_MainSite(7) = "网站描述"
	Keyicms_Lang_MainSite(8) = "学院名称"
    Keyicms_Lang_MainSite(9) = "学院地址"
    Keyicms_Lang_MainSite(10) = "联 系 人"
	Keyicms_Lang_MainSite(11) = "联系电话"
	Keyicms_Lang_MainSite(12) = "移动电话"
	Keyicms_Lang_MainSite(13) = "传真号码"
	Keyicms_Lang_MainSite(14) = "电子邮箱"
	Keyicms_Lang_MainSite(15) = "网站状态"
	Keyicms_Lang_MainSite(16) = "打开网站"
	Keyicms_Lang_MainSite(17) = "关闭网站"
	Keyicms_Lang_MainSite(18) = "关闭原因"
    Keyicms_Lang_MainSite(19) = "学院简介"
	
    Keyicms_Lang_MainSite(20) = "网站基本信息设置"
	Keyicms_Lang_MainSite(21) = "学院联系方式设置"
	Keyicms_Lang_MainSite(22) = "网站状态设置"
	Keyicms_Lang_MainSite(23) = "首页学院简介设置"
	Keyicms_Lang_MainSite(24) = "保存网站信息"
	Keyicms_Lang_MainSite(25) = "网站信息设置成功！"
	
'=========================================================
' 功能注释 : 系统后台语言文档(系统参数设置)
'=========================================================
Dim Keyicms_Lang_sys_Parameters(45)
    Keyicms_Lang_sys_Parameters(0) = "系统安装目录"
	Keyicms_Lang_sys_Parameters(1) = "数据库目录"
	Keyicms_Lang_sys_Parameters(2) = "防页面复制"
	Keyicms_Lang_sys_Parameters(3) = "后台登陆验证码"
	Keyicms_Lang_sys_Parameters(4) = "前台提交验证码"
	Keyicms_Lang_sys_Parameters(5) = "防注入系统"
	Keyicms_Lang_sys_Parameters(6) = "管理员认证码"
	Keyicms_Lang_sys_Parameters(7) = "管理员认证码设置"
	Keyicms_Lang_sys_Parameters(8) = "新闻模块调用条数"
    Keyicms_Lang_sys_Parameters(9) = "产品模块调用条数"
    Keyicms_Lang_sys_Parameters(10) = "案例模块调用条数"
	Keyicms_Lang_sys_Parameters(11) = "服务模块调用条数"
	Keyicms_Lang_sys_Parameters(12) = "团队模块调用条数"
	Keyicms_Lang_sys_Parameters(13) = "下载模块调用条数"
	Keyicms_Lang_sys_Parameters(14) = "其他信息调用条数"
	Keyicms_Lang_sys_Parameters(15) = "是否生成静态页面"
	Keyicms_Lang_sys_Parameters(16) = "后台汉字转换拼音"
	Keyicms_Lang_sys_Parameters(17) = "详细页面生成分隔符"
	Keyicms_Lang_sys_Parameters(18) = "产品模块主目录"
    Keyicms_Lang_sys_Parameters(19) = "新闻模块主目录"
    Keyicms_Lang_sys_Parameters(20) = "案例模块主目录"
	Keyicms_Lang_sys_Parameters(21) = "服务项目模块主目录"
	Keyicms_Lang_sys_Parameters(22) = "团队模块主目录"
	Keyicms_Lang_sys_Parameters(23) = "学院信息模块主目录"
	Keyicms_Lang_sys_Parameters(24) = "下载模块主目录"
	Keyicms_Lang_sys_Parameters(25) = "招聘模块主目录"
	Keyicms_Lang_sys_Parameters(26) = "其他信息模块主目录"
	Keyicms_Lang_sys_Parameters(27) = "单页模块主目录"
	Keyicms_Lang_sys_Parameters(28) = "浏览数设置"
    Keyicms_Lang_sys_Parameters(29) = "内页SEO设置"	

	Keyicms_Lang_sys_Parameters(31) = "网站安全设置"
	Keyicms_Lang_sys_Parameters(32) = "功能模块单页调用条数"
	Keyicms_Lang_sys_Parameters(33) = "静态化处理设置"
	Keyicms_Lang_sys_Parameters(34) = "其他信息设置"
	Keyicms_Lang_sys_Parameters(35) = "生成静态HTML"
	Keyicms_Lang_sys_Parameters(36) = "不生成静态"
    Keyicms_Lang_sys_Parameters(37) = "保存系统参数设置"
	Keyicms_Lang_sys_Parameters(38) = "系统参数设置成功！"
	Keyicms_Lang_sys_Parameters(39) = "删除成功！"
	
	Keyicms_Lang_sys_Parameters(40) = "目录及数据库设置"
	Keyicms_Lang_sys_Parameters(41) = "手机网站状态"	
	
'=========================================================
' 功能注释 : 系统后台语言文档(手机网站设置)
'=========================================================
Dim Keyicms_Lang_sys_Mobile(11)
    Keyicms_Lang_sys_Mobile(0) = "手机网站参数设置"
	Keyicms_Lang_sys_Mobile(1) = "是否自动跳转"
	Keyicms_Lang_sys_Mobile(2) = "手机网站标题"
	Keyicms_Lang_sys_Mobile(3) = "手机访问自动跳转"
	Keyicms_Lang_sys_Mobile(4) = "手机网站LOGO"
	Keyicms_Lang_sys_Mobile(5) = "手机网站关键词"
	Keyicms_Lang_sys_Mobile(6) = "手机网站描述"
	Keyicms_Lang_sys_Mobile(7) = "自动拨号电话"
    Keyicms_Lang_sys_Mobile(8) = "是否手机版显示"
    Keyicms_Lang_sys_Mobile(9) = "手机网站幻灯片"
    Keyicms_Lang_sys_Mobile(10) = "保存手机网站参数"
Dim Keyicms_Lang_ErrMsg(4)
    Keyicms_Lang_ErrMsg(0) = "的值数据库不存在，请检查！"
	Keyicms_Lang_ErrMsg(1) = "暂无相关信息"
	Keyicms_Lang_ErrMsg(2) = "Sort标签里SortType错误"
	Keyicms_Lang_ErrMsg(3) = "这条信息不存在"
	Keyicms_Lang_ErrMsg(4) = "未搜索到相关信息"
%>
