<link rel="shortcut icon" href="ke01/ico/favicon.png">
<!-- Bootstrap core CSS -->
<link href="ke01/css/bootstrap.min.css" rel="stylesheet">
<link href="ke01/css/jquery.mmenu.css" rel="stylesheet">

<!-- css页面 -->
<link href="ke01/css/font-awesome.min.css" rel="stylesheet">
<link href="ke01/plugins/jquery-ui/css/jquery-ui-1.10.4.min.css" rel="stylesheet">	

<!-- 模板的自定义样式 -->
<link href="ke01/css/style.min.css" rel="stylesheet">
<link href="ke01/css/add-ons.min.css" rel="stylesheet">

<link href="ke01/css/atom-style.css" rel="stylesheet">
<link href="ke01/css/minimal.css" rel="stylesheet">

<!-- 是IE8支持HTML5元素和Media Query -->
<!--[if lt IE 9]>-->
<script src="ke01/js/html5shiv.js"></script>
<script src="ke01/js/respond.min.js"></script>
<!--<![endif]-->
<!--[if !IE]>-->
<script type="text/javascript">window.jQuery || document.write("<scr"+"ipt src='ke01/js/jquery-2.1.1.min.js'>"+"<"+"/scr"+"ipt>");</script>
<!--<![endif]-->
<!--[if IE]>-->
<script type="text/javascript">window.jQuery || document.write("<scr"+"ipt src='ke01/js/jquery-1.11.1.min.js'>"+"<"+"/scr"+"ipt>");</script>
<!--<![endif]-->

<!-- SweetAlert -->
<link rel="stylesheet" type="text/css" href="SweetAlert/sweet-alert.css">
<script src="SweetAlert/sweet-alert.min.js"></script>