<!-- start: JavaScript-->
<script src="ke01/js/jquery-migrate-1.2.1.min.js"></script>
<script src="ke01/js/bootstrap.min.js"></script>	

<!-- page scripts -->
<script src="ke01/plugins/jquery-ui/js/jquery-ui-1.10.4.min.js"></script>

<!-- theme scripts -->
<script src="ke01/js/jquery.mmenu.min.js"></script>
<script src="ke01/js/core.min.js"></script>

<script src="ke01/plugins/datatables/js/jquery.dataTables.min.js"></script>
<script src="ke01/plugins/datatables/js/dataTables.bootstrap.min.js"></script>

<!-- inline scripts related to this page -->
<script src="ke01/js/pages/index.js"></script>
<script src="ke01/js/minimal.min.js"></script>	
<script src="ke01/js/Admin.js"></script>

<!-- end: JavaScript-->